# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lazy_student',
                'doc_host': 'https://frankausberlin.github.io',
                'git_url': 'https://github.com/frankausberlin/lazy_student',
                'lib_path': 'lazy_student'},
  'syms': {'lazy_student.core': {'lazy_student.core.foo': ('core.html#foo', 'lazy_student/core.py')}}}
